// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/auto-audio-mapper.js
// Run 'npm run map-audio' to regenerate

export const dictionaryAudioMap: Record<string, any> = {
  'ang': require('../../assets/audio/dictionary_words/ang-also_even.wav'),
  'arak': require('../../assets/audio/dictionary_words/arak-liquor.wav'),
  'arong_che': require('../../assets/audio/dictionary_words/arong_che-quite_big.wav'),
  'aze': require('../../assets/audio/dictionary_words/aze-fox.wav'),
  'ájo': require('../../assets/audio/dictionary_words/ájo-older_brother.wav'),
  'áma': require('../../assets/audio/dictionary_words/áma-mother.wav'),
  'áni': require('../../assets/audio/dictionary_words/áni-cousin.wav'),
  'áni': require('../../assets/audio/dictionary_words/áni-sister.wav'),
  'áwu': require('../../assets/audio/dictionary_words/áwu-father.wav'),
  'bang': require('../../assets/audio/dictionary_words/bang-wet.wav'),
  'bela': require('../../assets/audio/dictionary_words/bela-time.wav'),
  'bisa': require('../../assets/audio/dictionary_words/bisa-son.wav'),
  'bumo': require('../../assets/audio/dictionary_words/bumo-girl_daughter-1.wav'),
  'bumo': require('../../assets/audio/dictionary_words/bumo-girl_daughter.wav'),
  'bus': require('../../assets/audio/dictionary_words/bus-bus.wav'),
  'butsi': require('../../assets/audio/dictionary_words/butsi-mouse.wav'),
  'calai': require('../../assets/audio/dictionary_words/calai-run.wav'),
  'cappal': require('../../assets/audio/dictionary_words/cappal-sandal.wav'),
  'chang': require('../../assets/audio/dictionary_words/chang-beer.wav'),
  'che': require('../../assets/audio/dictionary_words/che-big-1.wav'),
  'choekhang': require('../../assets/audio/dictionary_words/choekhang-prayer_room.wav'),
  'chu': require('../../assets/audio/dictionary_words/chu-water-1.wav'),
  'chu': require('../../assets/audio/dictionary_words/chu-water.wav'),
  'cik': require('../../assets/audio/dictionary_words/cik-a_one.wav'),
  'cik': require('../../assets/audio/dictionary_words/cik-one-1.wav'),
  'cing': require('../../assets/audio/dictionary_words/cing-urine.wav'),
  'cunga': require('../../assets/audio/dictionary_words/cunga-little.wav'),
  'cunyí': require('../../assets/audio/dictionary_words/cunyí-twelve.wav'),
  'da': require('../../assets/audio/dictionary_words/da-now-1.wav'),
  'dakpo': require('../../assets/audio/dictionary_words/dakpo-ownership.wav'),
  'danda': require('../../assets/audio/dictionary_words/danda-now-1.wav'),
  'danda': require('../../assets/audio/dictionary_words/danda-now.wav'),
  'dang': require('../../assets/audio/dictionary_words/dang-and-1.wav'),
  'dangsang': require('../../assets/audio/dictionary_words/dangsang-fine.wav'),
  'dawa': require('../../assets/audio/dictionary_words/dawa-month.wav'),
  'denchak': require('../../assets/audio/dictionary_words/denchak-stay_sit.wav'),
  'denchak_o': require('../../assets/audio/dictionary_words/denchak_o-goodbye.wav'),
  'dene': require('../../assets/audio/dictionary_words/dene-then-1.wav'),
  'dene': require('../../assets/audio/dictionary_words/dene-then_after_that.wav'),
  'dering': require('../../assets/audio/dictionary_words/dering-today-1.wav'),
  'dering': require('../../assets/audio/dictionary_words/dering-today.wav'),
  'di': require('../../assets/audio/dictionary_words/di-this-1.wav'),
  'di': require('../../assets/audio/dictionary_words/di-this.wav'),
  'dikpa': require('../../assets/audio/dictionary_words/dikpa-sin.wav'),
  'dokur': require('../../assets/audio/dictionary_words/dokur-basket.wav'),
  'dongpo': require('../../assets/audio/dictionary_words/dongpo-tree.wav'),
  'dranga': require('../../assets/audio/dictionary_words/dranga-cold.wav'),
  'dre': require('../../assets/audio/dictionary_words/dre-mule.wav'),
  'dro': require('../../assets/audio/dictionary_words/dro-go.wav'),
  'dro': require('../../assets/audio/dictionary_words/dro-to_go.wav'),
};

export function normalizeDzKey(input: string): string {
  // lower, strip accents, replace spaces with underscore
  const lower = input.toLowerCase();
  const stripped = lower.normalize('NFD').replace(/\p{M}+/gu, '');
  return stripped.replace(/\s+/g, '_');
}
