// Auto-generated by scripts/generate-image-registry.ts
import type { ImageSourcePropType } from 'react-native';

const imageRegistry: Record<string, ImageSourcePropType> = {
  'bats.png': require('../../assets/images/animals/bats.png'),
  'birds.png': require('../../assets/images/animals/birds.png'),
  'black-birds.png': require('../../assets/images/animals/black-birds.png'),
  'butterflies.png': require('../../assets/images/animals/butterflies.png'),
  'fish.png': require('../../assets/images/animals/fish.png'),
  'foxes.png': require('../../assets/images/animals/foxes.png'),
  'monkeys.png': require('../../assets/images/animals/monkeys.png'),
  'turtles.png': require('../../assets/images/animals/turtles.png'),
  'two-frogs.png': require('../../assets/images/animals/two-frogs.png'),
  'white-dog.png': require('../../assets/images/animals/white-dog.png'),
};

export default imageRegistry;
